services:
  calculadora:
    image: calculadora-propina
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules